config/routes.rb
Rails.application.routes.draw do
  root "pokemon#index"
  resources :pokemon, only: [:index, :new, :create, :show]
  get '/pokemon/random_pokemon/:id', to: 'pokemon#random_pokemon',:action=>"show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon<ApplicationRecord
  validates_presence_of :name, :order, :weight, :image_url, :poke_type, :poke_ability
  validates_uniqueness_of :name, :order
  def self.create_pokemon(data)
    create(
      name: data.name,
      order: data.order,
      image_url: data.image_url,
      weight: data.weight,
      poke_type: data.poke_type,
      poke_ability: data.poke_ability
    )
    # Pokemon.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_controller.rb
require 'pokemon_request'
class PokemonController < ApplicationController
  # skip_before_action :verify_authenticity_token
  def index
    # pokemons=Pokemon.all.delete_all
    pokemons=PokemonRequest.get_all_pokemons
    pokemons.each do |poke|
      @pokemon=Poke.new(poke)
    @pokemon=Pokemon.create_pokemon(@pokemon)
    end
    @pokemons=Pokemon.order(:id).page(params[:page])
  end

  def new
     pokemon=params[:pokemon]
      pokemon=PokemonRequest.get_pokemon(pokemon)
      if !pokemon.nil?
        poke=Poke.new(pokemon)
        @pokemon=Pokemon.create_pokemon(poke)
      else
        redirect_to root_path
      end
  end
  def show
    @pokemon = Pokemon.find(params[:id])
  end
  #
  def random_pokemon
    @random_pokemon = Pokemon.find(rand(Pokemon.first.id..Pokemon.last.id))
    # @random_pokemon = Pokemon.find(rand(1..Pokemon.count))
    # @random_pokemon=Pokemon.all.shuffle.last
    # @random_pokemon=Pokemon.find(Pokemon.pluck(:id).sample(1))
    # @random_pokemon=Pokemon.limit(1).order("RANDOM()")
  end





  private
  def pokemon_params
    params.require(:pokemon).permit(:order, :name, :image_url, :weight, :poke_type, :poke_ability)
  end
  end

app/views/pokemon/index.html.erb
<%= stylesheet_link_tag '/assets/poke' , media: 'all'%>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render "shared/nav" %>

<div class="cards">
<% if @pokemons.nil? %>
<p> no pokemons</p>
<% else %>
    <% @pokemons.each do |pokemon| %>
<%= render partial: 'shared/card', locals: {pokemon: pokemon} %>
<% end %>
<% end %>
</div>
<div class="pagination">
<!--  <p><%#= page_entries_info @pokemons %></p>-->
  <p><%= paginate @pokemons %></p>
</div>

app/views/pokemon/new.html.erb
<%= stylesheet_link_tag '/assets/poke' , media: 'all'%>
<%= render "shared/nav" %>
<h1>Search pokemon by name or number!</h1>

<%= render "shared/search", { path: new_pokemon_path } %>
<% if @pokemon.name.nil? %>
  <p> no such pokemon</p>
<% else %>
  <%= render partial: 'shared/card', locals: {pokemon: @pokemon} %>
<% end %>

app/views/pokemon/random_pokemon.html.erb
<%= stylesheet_link_tag '/assets/poke' , media: 'all'%>
<%= render "shared/nav" %>
<div class="cards">
    <%= render partial: 'shared/card', locals: {pokemon: @random_pokemon} %>
</div>

app/views/pokemon/show.html.erb
<%= stylesheet_link_tag '/assets/poke' , media: 'all'%>
<%= render "shared/nav" %>
<div class="show-card">
  <% if @pokemon.present? %>
  <div class="picture-card">
  <p class="card-name"> <%= @pokemon.name %></p>
    <%= image_tag(@pokemon.image_url, size: "300") %>
    </div>
    <div class="info-card">
        <p>No. <%= @pokemon.order %></p>
        <p>Weight: <%= @pokemon.weight %></p>
        <p>Type: <%= @pokemon.poke_type %></p>
        <p>Ability: <%= @pokemon.poke_ability %></p>
    </div>
    </div>
  <% end %>

app/views/shared/_card.html.erb
<div class="card">

  <div class="card-item">
    <%=link_to pokemon.name, pokemon_path(pokemon.id) %>
    <p>No.  <%= pokemon.order %></p>
  </div>
  <div class="card-item">
    <p>Name:  <%= pokemon.name %></p>
  </div>
  <div class="card-picture">
    <%= image_tag(pokemon.image_url, size: "200") if pokemon.image_url %>
  </div>
</div>

app/views/shared/_nav.erb
<div class="navbar ">
  <div class="nav-brand">
    <%= image_tag "pngwing.png", height: 50 %>
  </div>
  <div class="nav-container">
    <li class="nav-item">
      <%= link_to 'Home', pokemon_index_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Search Pokemon',new_pokemon_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Random Pokemon',  '/pokemon/random_pokemon/:id', class: 'nav-link' %>
    </li>
  </div>
</div>

app/views/shared/_search.html.erb
<div style="margin-bottom: 50px;">
  <%= form_with url: path, method: :get, local: true do |form| %>
    <%= form.number_field  :pokemon %>
    <%= form.submit 'search', name: nil %>
  <% end %>
</div>